version: '3.1'

services:

  mongo:
    image: mongo:4
    restart: always
    ports:
      - 27017:27017

  server:
    build: ./
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on: 
      - mongo
    ports: 
      - 3001:3001



version: '3.1'

services:

  mongo:
    image: mongo:4
    ports:
      - 27017:27017

  server:
    image: joxmar/booking
    ports:
      - 3001:3001

